OBJS = runtest overflow str getdigits
CC = g++

all: runtest

main:
	$(CC) runtest.cpp -o main

overflow:
	$(CC) overflow.cpp -o overflow

str:
	$(CC) str.cpp -o str

getdigits:
	$(CC) getdigits.cpp -o getdigits

clean:
	rm -rf $(OBJS)